AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - 'bin/bundle'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'spec/rails_helper.rb'